# Generated by Django 6.0.3 on 2026-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_options',
            field=models.JSONField(default=list),
        ),
    ]
